# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GuillotineApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuillotineApp
  pod 'Alamofire', '~> 4.7'
  pod 'UICKeyChainStore', '~> 2.0.6'
  pod 'AWSCognito', '~> 2.2.5'
  pod 'FBSDKCoreKit', '~> 4.9'
  pod 'FBSDKLoginKit', '~> 4.9'
  pod 'FBSDKShareKit', '~> 4.9'

  target 'GuillotineAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuillotineAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
